### ISSUE TITLE
如何实现Picker组件的国际化

### ISSUE THREAD

**Issue by zhuhyun** [ladybirdDEV/ui-nuclear-mobile#10]
### 问题描述：
```Picker```组件是由底层组件```MobilePicker```封装实现的，组件内的文字是由父组件```prop```，在底层组件渲染，如果上层组件没有```prop```，则渲染默认的值。
```Picker```组件```prop```属性：
```
 okText: {
      type: String,
      default: '确定'
    },
 dismissText: {
      type: String,
      default: '取消'
    },
 title: String
```
目前无法将语言包的值```currentLocale.xxx```传给底层组件，不能实现国际化。
#### 需要思考的问题：
* 在底层组件实现多语言，组件```<LocaleProvider>```包裹是否有效？
* 后期底层组件可能会抽出来成为一个单独的项目，这种方式实现国际化是否有影响？

**Comment by tortorse** [comment]
底层组件注入是不是可以？

**Comment by tortorse** [comment]
Picker本身是字面量给M-picker的呀，直接字面量把inject过来的数据给到下层不行吗？

**Comment by zhuhyun** [comment]
#### 目前实现的方式：
* 在Picker组件中注入```LocaleProvider```组件的语言包
* 底层组件```MobilePopup```提供```locale```接口，Picker组件通过该接口将```computed```的```currentLocale``` 对象传给底层组件
* 另外底层组件中需要国际化的内容也可以由```prop```对象实现，删除对应变量设置的默认值，判断父组件是否传值，如果没有则渲染父组件传入的语言包的内容：```{{dismissText || locale.dismissText}}```

**Comment by tortorse** [comment]
实现了话，发PR吧

**Comment by zhuhyun** [comment]
已修复 #36
