### ISSUE TITLE
单独引入组件路径问题

### ISSUE THREAD

**Issue by QueenieMar** [ladybirdDEV/ui-nuclear-mobile#140]
单独引入组件时，报错，如下图
![image](https://user-images.githubusercontent.com/19548158/42306559-0a763f28-8062-11e8-80cf-9edcb978bbb6.png)

**Comment by tortorse** [comment]
该问题已修复 #142 
但需要重新发包才能进行测试
@QueenieMar

**Comment by tortorse** [comment]
其他组件也存在同样的问题，一并修复 #144
