### ISSUE TITLE
将🤖的token权限降低后，测试是否能关闭并添加label

### ISSUE THREAD

**Issue by tortorse** [ladybirdDEV/ui-nuclear-mobile#16]
不合格的issue，需要被关闭和加上invalid标签

**Comment by ladybirdstudio** [comment]
hi @tortorse，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://xuexb.github.io/github-bot/create-issue.html) 页面提交， 将直接被关闭， 谢谢！

**Comment by tortorse** [comment]
标签正常，但没有关闭
