### ISSUE TITLE
datePicker组件的bug

### ISSUE THREAD

**Issue by artiely** [ladybirdDEV/ui-nuclear-mobile#210]
datePicker里的date和dateTime在iphone7s下没有显示年份，其他安卓机上正常

**Comment by tortorse** [comment]
能否给个手机上的截图

**Comment by artiely** [comment]
![Uploading IMG_0726.PNG…]()



类似如此（上传出错就传这一张）

**Comment by tortorse** [comment]
问题已确认 ，尽快修复

**Comment by tortorse** [comment]
已修复

**Comment by tortorse** [comment]
> 日期字符串在不同浏览器有不同的实现，例如 new Date('2017-1-1') 在 Safari 上是 Invalid Date，而在 Chrome 上是能正常解析的。
兼容方法是 
```javascript
new Date('2018/07/01')
```
