### ISSUE TITLE
组件文档不完善

### ISSUE THREAD

**Issue by ljmCoder** [ladybirdDEV/ui-nuclear-mobile#224]
组件内用到的一些props在文档上没有完全写出来，漏了一些props

**Comment by ljmCoder** [comment]
![image](https://user-images.githubusercontent.com/41459781/43059625-ef148b14-8e7f-11e8-9b6b-b9fc0df35274.png)

![image](https://user-images.githubusercontent.com/41459781/43059760-a23f8018-8e80-11e8-90a8-ba9f158c5313.png)

carousel组件使用时 有传一些props进去，但是在说明文档中并未标注暴露这些props

**Comment by tortorse** [comment]
已修复 #225
