### ISSUE TITLE
Pannel的直接父节点必须是According

### ISSUE THREAD

**Issue by cnAlexJiang** [ladybirdDEV/ui-nuclear-mobile#233]
Pannel实现的源码中，有这句话
![image](https://user-images.githubusercontent.com/22976188/44135962-a718bbb6-a09d-11e8-800b-fc7344eb5a35.png)
因此，导致其parent如果不是According或者其parent中没有toggle，则报错。
建议修改实现，递归寻找$parent.toggle方法，并做找到与找不到的处理

**Comment by tortorse** [comment]
fix #234
