### ISSUE TITLE
导航优化问题

### ISSUE THREAD

**Issue by QueenieMar** [ladybirdDEV/ui-nuclear-mobile#25]
![image](https://user-images.githubusercontent.com/19548158/41274779-3af25ff6-6e51-11e8-8b8b-8c3c445216a7.png)
返回按钮的shijia事件最好不要代理浏览器的history；
进入某一个组件的展示页面，“首页”两个字是不是应该换成该组件的名字。

**Comment by tortorse** [comment]
已修改 #26
