### ISSUE TITLE
Result组件中message插槽不显示的问题

### ISSUE THREAD

**Issue by skottiewang** [ladybirdDEV/ui-nuclear-mobile#251]
![image](https://user-images.githubusercontent.com/9428451/53852438-fe2a3c00-3ffc-11e9-8533-3dc52e2ce5a4.png)
![image](https://user-images.githubusercontent.com/9428451/53852487-29ad2680-3ffd-11e9-84a2-76468002edb7.png)

Result组件文档中的message插槽没有显示出来

**Comment by tortorse** [comment]
已修复，将在下一版本发布到npm
