### ISSUE TITLE
Popover的宽度被写死为`135px`

### ISSUE THREAD

**Issue by tortorse** [ladybirdDEV/ui-nuclear-mobile#48]
![image](https://user-images.githubusercontent.com/10540493/41578029-cc6ddae8-73c2-11e8-8944-fa9f73921f61.png)

应该由内部元素的宽度来决定

## antd 里并没有写死宽度
![image](https://user-images.githubusercontent.com/10540493/41578092-1064ef8e-73c3-11e8-8d3c-f197d4cbcbab.png)

**Comment by QueenieMar** [comment]
fixed
