### ISSUE TITLE
`PickerView`的 value prop 默认值错误

### ISSUE THREAD

**Issue by tortorse** [ladybirdDEV/ui-nuclear-mobile#51]
![image](https://user-images.githubusercontent.com/10540493/41632626-644acfec-746d-11e8-8ea5-b09122b8e188.png)

在源码中：

```javascript
    value: {
      type: Array,
      default: []
    }
```

vue 中要求如果默认值是对象或数组，需要用一个工厂函数来返回

https://cn.vuejs.org/v2/guide/components-props.html#Prop-%E9%AA%8C%E8%AF%81

**Comment by QueenieMar** [comment]
fixed already
