### ISSUE TITLE
`Modal`组件在出现时会增加高度，消失时没有去除

### ISSUE THREAD

**Issue by tortorse** [ladybirdDEV/ui-nuclear-mobile#62]
![image](https://user-images.githubusercontent.com/10540493/41649351-f5cb7a08-74ad-11e8-982c-aa220af96f7a.png)

会将整个界面撑大一倍

![image](https://user-images.githubusercontent.com/10540493/41649398-0dda24aa-74ae-11e8-8ca9-208dc1cba4d8.png)

**Comment by QueenieMar** [comment]
fixed
